# This file lists tools managed by Rokit, a toolchain manager for Roblox projects.
# For more information, see https://github.com/rojo-rbx/rokit

# New tools can be added by running `rokit add <tool>` in a terminal.

[tools]
blink = "1Axen/blink@0.18.6"
rojo = "rojo-rbx/rojo@7.5.1"
wally = "UpliftGames/wally@0.3.2"
stylua = "JohnnyMorganz/stylua@2.1.0"
wally-package-types = "JohnnyMorganz/wally-package-types@1.5.1"
luau-lsp = "JohnnyMorganz/luau-lsp@1.53.1"
zap = "red-blox/zap@0.6.25"
